CREATE TABLE projjetta.stg_dado_aberto_socio
(
  NUM_CNPJ_RAIZ BIGINT
, TIP_SOCIO BIGINT
, NOM_SOCIO VARCHAR(160)
, NUM_CNPJ_CPF VARCHAR(14)
, COD_QUALIFICACAO BIGINT
, DAT_ENTRADA_SOCIEDADE TIMESTAMP
, COD_PAIS BIGINT
, NUM_CPF_REPRESENTANTE VARCHAR(11)
, NOM_REPRESENTANTE VARCHAR(60)
, COD_QUALIFICACAO_REPRESENTANTE BIGINT
, COD_FAIXA_ETARIA BIGINT
)
;