CREATE TABLE projjetta.stg_dado_aberto_simples
(
  NUM_RAIZ_CNPJ BIGINT
, IND_SIMPLES VARCHAR(1)
, DAT_OPTANTE TIMESTAMP
, DAT_EXCLUSAO TIMESTAMP
, IND_MEI VARCHAR(1)
, DAT_OPTANTE_MEI TIMESTAMP
, DAT_EXCLUSAO_MEI TIMESTAMP
)
;