CREATE TABLE projjetta.stg_dado_aberto_empresa
(
  NUM_RAIZ_CNPJ BIGINT
, NOM_RAZAO_SOCIAL VARCHAR(100)
, COD_NATUREZA_JURIDICA BIGINT
, COD_QUALIFICACAO_RESPONSAVEL BIGINT
, VAL_CAPITAL_SOCIAL NUMERIC(15, 2)
, COD_PORTE_EMPRESA BIGINT
, DES_ENTE_FEDERATIVO TEXT
)
;